require("config.base")
require("config.lazy")
require("config.lualine")
require("config.noice")
require("config.autocompletions")
require("config.nvimtree")
require("config.telescope")
require("mason").setup()
